KioskWebWizard/KioskWebWizard/Controllers/KioskController.cs
using System;
using System.Collections.Generic;
using KioskWebWizard.Models;
using KioskWebWizard.Services.Interfaces;
using KioskWebWizard.ViewModel.Kiosk;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using KioskWebWizard.ViewModel.Kiosk.Run;

namespace KioskWebWizard.Controllers
{
    public class KioskController : Controller
    {
        private readonly IKioskService _kioskService;
        private readonly UserManager<IdentityUser> _userManager;

        public KioskController(IKioskService kioskService, UserManager<IdentityUser> userManager)
        {
            _kioskService = kioskService;
            _userManager = userManager;
        }

        // GET: KioskController
        public IActionResult Index()
        {
            var kiosksList = _kioskService.GetAllByLoggedUser(User.Identity.Name);
            List<KioskListViewModel> kioskListViewModel = new List<KioskListViewModel>();
            foreach (var plan in kiosksList)
            {
                kioskListViewModel.Add(new KioskListViewModel
                {
                    ID = plan.ID,
                    Name = plan.Name
                });
            }
            return View(kioskListViewModel);
        }
        [HttpGet]
        // GET: KioskController/Details/5
        public IActionResult Details(int KioskID)
        {
            if (_kioskService.CheckForTemplateID(KioskID) == 1)
            {
                return RedirectToAction(nameof(Details1), new { KioskID });
            }
            if (_kioskService.CheckForTemplateID(KioskID) == 2)
            {
                return RedirectToAction(nameof(Details2), new { KioskID });
            }
            else
                return View();
        }
        [HttpGet]
        public IActionResult Details1(int KioskID)
        {
            try
            {
                var kioskModel = _kioskService.Get(KioskID);
                var result = new KioskDetailViewModel1
                {
                    ID = kioskModel.ID,
                    Name = kioskModel.Name,
                    TemplateName = _kioskService.GetTemplateNameByID(KioskID),
                };
                return View(result);
            }
            catch (Exception e)
            {
                //return Content(e.ToString());
            }
            return View();
        }
        [HttpGet]
        public IActionResult Details2(int KioskID)
        {
            try
            {
                var kioskModel = _kioskService.Get(KioskID);
                var result = new KioskDetailViewModel2
                {
                    ID = kioskModel.ID,
                    Name = kioskModel.Name,
                    TemplateName = _kioskService.GetTemplateNameByID(KioskID)
                };
                return View(result);
            }
            catch (Exception e)
            {
                //return Content(e.ToString());
            }
            return View();
        }

        // GET: KioskController/Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["KioskTemplate"] = _kioskService.GetKioskTemplateList();
            return View();
        }

        // POST: KioskController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(KioskInitialCreateViewModel kioskInitialCreateView)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var model = new KioskModel
                    {
                        KioskTemplateID = kioskInitialCreateView.KioskTemplateID,
                        Name = kioskInitialCreateView.Name,
                        UserId = _userManager.GetUserId(User),
                    };
                    _kioskService.Create(model);

                    if (model.KioskTemplateID == 1)
                    {
                        var model1 = new KioskCreateViewModel1
                        {
                            KioskID = model.ID
                        };
                        TempData["kioskCreate1"] = JsonSerializer.Serialize(model1);
                        return RedirectToAction(nameof(Create1));
                    }

                    if (model.KioskTemplateID == 2)
                    {
                        var model2 = new KioskCreateViewModel2
                        {
                            KioskID = model.ID
                        };
                        TempData["kioskCreate2"] = JsonSerializer.Serialize(model2);
                        return RedirectToAction(nameof(Create2));
                    }
                    else
                        return default;

                    //return RedirectToAction(nameof(CreateNext), new { kioskID = model.ID });
                }
                catch
                {
                    return View(kioskInitialCreateView);
                }
            }
            else
            {
                return View(kioskInitialCreateView);
            }
        }


        [HttpGet]
        public IActionResult Create1()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create1(KioskCreateViewModel1 kioskCreateViewModel1)
        {
            KioskCreateViewModel1 tempModel = JsonSerializer.Deserialize<KioskCreateViewModel1>((string)TempData["kioskCreate1"]);
            kioskCreateViewModel1.KioskID = tempModel.KioskID;
            if (ModelState.IsValid)
            {
                try
                {
                    var model = new KioskLoyaltyTemplateDataModel
                    {
                        LoyaltyName = kioskCreateViewModel1.LoyaltyName,
                        LoyaltyDescription = kioskCreateViewModel1.LoyaltyDescription,
                        LoyaltyCarouselData1 = kioskCreateViewModel1.LoyaltyCarouselData1,
                        LoyaltyCarouselData2 = kioskCreateViewModel1.LoyaltyCarouselData2,
                        LoyaltyCarouselData3 = kioskCreateViewModel1.LoyaltyCarouselData3,
                        LoyaltyCarouselData4 = kioskCreateViewModel1.LoyaltyCarouselData4,
                        LoyaltyCarouselData5 = kioskCreateViewModel1.LoyaltyCarouselData5
                    };
                    _kioskService.Create1(model);
                    var kioskModel = _kioskService.Get(kioskCreateViewModel1.KioskID);
                    kioskModel.KioskLoyaltyTemplateDataID = model.ID;
                    _kioskService.Update(kioskModel);
                    return RedirectToAction("Details", new { KioskID = kioskModel.ID });
                }
                catch
                {
                    return View(kioskCreateViewModel1);
                }
            }
            else
            {
                return View(kioskCreateViewModel1);
            }
        }

        [HttpGet]
        public IActionResult Create2()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create2(KioskCreateViewModel2 kioskCreateViewModel2)
        {
            KioskCreateViewModel2 tempModel = JsonSerializer.Deserialize<KioskCreateViewModel2>((string)TempData["kioskCreate2"]);
            kioskCreateViewModel2.KioskID = tempModel.KioskID;
            if (ModelState.IsValid)
            {
                try
                {
                    var model = new KioskMapTemplateDataModel
                    {
                        MapName = kioskCreateViewModel2.MapName,
                    };
                    _kioskService.Create2(model);
                    var kioskModel = _kioskService.Get(kioskCreateViewModel2.KioskID);
                    kioskModel.KioskMapTemplateDataID = model.ID;
                    _kioskService.Update(kioskModel);
                    return RedirectToAction("Details", new { KioskID = kioskModel.ID });

                }
                catch
                {
                    return View(kioskCreateViewModel2);
                }
            }
            else
            {
                return View(kioskCreateViewModel2);
            }
        }

        // GET: KioskController/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var kioskToBeEdited = _kioskService.Get(id);
            KioskEditViewModel kioskEditViewModel = new KioskEditViewModel
            {
                ID = kioskToBeEdited.ID,
                Name = kioskToBeEdited.Name,
                KioskTemplate = kioskToBeEdited.KioskTemplate,
            };
            return View(kioskEditViewModel);
        }

        // POST: KioskController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, KioskEditViewModel kioskEditViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var kioskModel = _kioskService.Get(kioskEditViewModel.ID);
                    kioskModel.ID = kioskEditViewModel.ID;
                    kioskModel.Name = kioskEditViewModel.Name;
                    kioskModel.KioskTemplate = kioskEditViewModel.KioskTemplate;

                    _kioskService.Update(kioskModel);
                    return RedirectToAction("Details", new { id = kioskEditViewModel.ID });
                }
                catch
                {
                    return View(kioskEditViewModel);
                }
            }
            else
            {
                return View(kioskEditViewModel);
            }
        }

        // GET: KioskController/Delete/5
        public IActionResult Delete(int id)
        {
            var deleteKiosk = _kioskService.Get(id);
            KioskDeleteViewModel kioskDeleteViewModel = new KioskDeleteViewModel
            {
                ID = deleteKiosk.ID,
                Name = deleteKiosk.Name,
            };

KioskWebWizard/KioskWebWizard/Views/Kiosk/Create.cshtml
@model KioskWebWizard.ViewModel.Kiosk.KioskInitialCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Utwórz nowy kiosk</h2>
<hr />
<div class="table text-md-center d-flex justify-content-center pt-lg-5">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nazwa kiosku</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
                <label asp-for="KioskTemplate" class="control-label">Wybierz szablon dla kiosku</label>
                <select asp-for="@Model.KioskTemplateID" class="form-control" asp-items="ViewBag.KioskTemplate">
                </select>
                <span asp-validation-for="KioskTemplate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Wróc do strony głównej</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KioskWebWizard/KioskWebWizard/Views/Kiosk/Create1.cshtml
@model KioskWebWizard.ViewModel.Kiosk.KioskCreateViewModel1

@{
    ViewData["Title"] = "Create1";
}

<h2>Podaj dane dotyczące kiosku dla programu lojalnościowego</h2>
<hr />
<div class="table text-md-center d-flex justify-content-center pt-lg-5">
    <div class="col-md-4">
        <form asp-action="Create1">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LoyaltyName" class="control-label">Nazwa programu lojalnościowego</label>
                <input asp-for="LoyaltyName" class="form-control" />
                <span asp-validation-for="LoyaltyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyaltyDescription" class="control-label">Opis programu lojalnościowego</label>
                <input asp-for="LoyaltyDescription" class="form-control" />
                <span asp-validation-for="LoyaltyDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyaltyCarouselData1" class="control-label">Pozycja numer 1 informacji wyświetlanych na stronie startowej</label>
                <input asp-for="LoyaltyCarouselData1" class="form-control" />
                <span asp-validation-for="LoyaltyCarouselData1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyaltyCarouselData2" class="control-label">Pozycja numer 2 informacji wyświetlanych na stronie startowej</label>
                <input asp-for="LoyaltyCarouselData2" class="form-control" />
                <span asp-validation-for="LoyaltyCarouselData2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyaltyCarouselData3" class="control-label">Pozycja numer 3 informacji wyświetlanych na stronie startowej</label>
                <input asp-for="LoyaltyCarouselData3" class="form-control" />
                <span asp-validation-for="LoyaltyCarouselData3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyaltyCarouselData4" class="control-label">Pozycja numer 4 informacji wyświetlanych na stronie startowej</label>
                <input asp-for="LoyaltyCarouselData4" class="form-control" />
                <span asp-validation-for="LoyaltyCarouselData4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoyaltyCarouselData5" class="control-label">Pozycja numer 5 informacji wyświetlanych na stronie startowej</label>
                <input asp-for="LoyaltyCarouselData5" class="form-control" />
                <span asp-validation-for="LoyaltyCarouselData5" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Wróc do strony głównej</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KioskWebWizard/KioskWebWizard/Views/Kiosk/Create2.cshtml
@model KioskWebWizard.ViewModel.Kiosk.KioskCreateViewModel2

@{
    ViewData["Title"] = "Create2";
}

<h2>Podaj dane dotyczące kiosku z mapą interaktywną</h2>
<hr />
<div class="table text-md-center d-flex justify-content-center pt-lg-5">
    <div class="col-md-4">
        <form asp-action="Create2">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MapName" class="control-label">Nazwa Mapy</label>
                <input asp-for="MapName" class="form-control" />
                <span asp-validation-for="MapName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Wróc do strony głównej</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KioskWebWizard/KioskWebWizard/Views/Kiosk/CreateTemplate.cshtml
@model KioskWebWizard.ViewModel.Kiosk.TemplateCreateViewModel

@{
    ViewData["Title"] = "CreateTemplate";
}

<h2>Utwórz szablon dla kiosku</h2>
<hr />
<div class="table text-md-center d-flex justify-content-center pt-lg-5">
    <div class="col-md-4">
        <form asp-action="CreateTemplate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TemplateName" class="control-label">Nazwa Szablonu</label>
                <input asp-for="TemplateName" class="form-control" />
                <span asp-validation-for="TemplateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Wróc do strony głównej</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KioskWebWizard/KioskWebWizard/Views/Kiosk/Details1.cshtml
@model KioskWebWizard.ViewModel.Kiosk.KioskDetailViewModel1

@{
    ViewData["Title"] = "Details1";
}

<h2>Szczegółowe informacje o kiosku programu lojalnościowego</h2>
<hr />
<div>  
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TemplateName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TemplateName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edycja", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index" asp-controller="Home">Wróc do strony głównej</a>
</div>

KioskWebWizard/KioskWebWizard/Views/Kiosk/Details2.cshtml
@model KioskWebWizard.ViewModel.Kiosk.KioskDetailViewModel2

@{
    ViewData["Title"] = "Details2";
}

<h2>Szczegółowe informacje o kiosku dla mapy interaktywnej</h2>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TemplateName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TemplateName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edycja", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index" asp-controller="Home">Wróc do strony głównej</a>
</div>

KioskWebWizard/KioskWebWizard/Views/Kiosk/Index.cshtml
@model IEnumerable<KioskWebWizard.ViewModel.Kiosk.KioskListViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Spis wszystkich utworzonych kiosków</h2>
<p>
    <a asp-action="Create">Utwórz nowy kiosk</a>
</p>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TemplateName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TemplateName)
            </td>
            <td>
                @Html.ActionLink("Edycja", "Edit", new { KioskID = item.ID }) |
                @Html.ActionLink("Szczegóły", "Details", new { KioskID = item.ID }) |
                @Html.ActionLink("Usuń", "Delete", new { KioskID = item.ID }) |
                @Html.ActionLink("Uruchom", "Run", new { KioskID = item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

KioskWebWizard/KioskWebWizard/Views/Kiosk/Run1.cshtml
@model KioskWebWizard.ViewModel.Kiosk.Run.KioskRun1ViewModelPart1

@{
    ViewData["Title"] = "Run1";
}
<div class="container">
    <h1>@Model.LoyaltyName</h1>
    <p class="lead">@Model.LoyaltyDescription</p>
</div>
<div class="container bg-secondary text-white heig">
    <div id="carouselContent" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active text-center p-xl-5">
                <p>@Model.LoyaltyCarouselData1</p>
            </div>
            <div class="carousel-item text-center p-xl-5">
                <p>@Model.LoyaltyCarouselData2</p>
            </div>
            <div class="carousel-item text-center p-xl-5">
                <p>@Model.LoyaltyCarouselData3</p>
            </div>
            <div class="carousel-item text-center p-xl-5">
                <p>@Model.LoyaltyCarouselData4</p>
            </div>
            <div class="carousel-item text-center p-xl-5">
                <p>@Model.LoyaltyCarouselData5</p>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselContent" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselContent" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="container text-center p-5">
    <button type="button" class="btn btn-success btn-lg" onclick="window.location='@Url.Action("Run11", "Kiosk")'">Wstąp już Dziś!</button>
</div>

KioskWebWizard/KioskWebWizard/Views/Kiosk/Run11.cshtml
@model KioskWebWizard.ViewModel.Kiosk.Run.KioskRun11CreateUserViewModel

@{
    ViewData["Title"] = "Run11";
}

<h3 class="pt-lg-5">Uzupełnij dane, abyśmy mogli założyć Ci konto klienta</h3>
<hr />
<div class="table text-md-center d-flex justify-content-center pt-lg-5">
    <div class="col-md-4">
        <form asp-action="Run11">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label">Adres e-mail</label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Hasło</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RepeatPassword" class="control-label">Powtórz Hasło</label>
                <input asp-for="RepeatPassword" class="form-control" />
                <span asp-validation-for="RepeatPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dalej" class="btn btn-primary" />
                
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KioskWebWizard/KioskWebWizard/Views/Kiosk/Run14.cshtml
@model KioskWebWizard.ViewModel.Kiosk.Run.KioskRun14CreateUserViewModel

@{
    ViewData["Title"] = "Run14";
}

<h3 class="pt-lg-5">Sprawdź proszę, czy dane się zgadzają?</h3>
<hr />
<div class="table d-flex justify-content-center pt-lg-5">
        <dl class="table">
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.Firstname)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Firstname)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.Lastname)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Lastname)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.EmailAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EmailAddress)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.AllowAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AllowAddress)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.Street)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Street)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.BuildingNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BuildingNumber)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.ApartmentNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ApartmentNumber)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.PostalCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PostalCode)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City)
            </dd>
            <dt class="col-sm-2 text-sm-left">
                @Html.DisplayNameFor(model => model.Country)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Country)
            </dd>
        </dl>
    </div>
<div class="table pt-lg-2">
    <div class="col-md-4">
        <form asp-action="Run14">
            <div class="form-group">
                <span>
                    <input asp-for="Rodo" class="form-control" />
                </span>
                <span>
                    <label asp-for="Rodo" class="control-label"></label>
                </span>
                <span asp-validation-for="Rodo" class="text-danger"></span>
</div>
            <div class="form-group">

            </div>
        </form>
    </div>
</div>
    <div class="container text-center p-5">
        <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("RunYes", "Kiosk")'">TAK</button>
        <button type="button" class="btn btn-danger" onclick="window.location='@Url.Action("RunNo", "Kiosk")'">Nie</button>
    </div>

KioskWebWizard/KioskWebWizard/Views/Kiosk/Run15.cshtml
@model KioskWebWizard.ViewModel.Kiosk.Run.KioskRun15CreateUserViewModel

@{
    ViewData["Title"] = "Run15";
}
<h2 class="pt-lg-5">Witamy w programie stałego klienta!</h2>
<h4 class="pt-lg-1">Oto Twój unikatowy numer klienta. Został on także wysłany do Ciebie na podany adres e-mail</h4>
<hr />
<div class="text-center">
    <h1>@Html.DisplayFor(model => model.LoyaltyID)</h1>
</div>
<div class="d-flex justify-content-center pt-3">
    <button type="button" class="btn btn-success btn-lg " onclick="window.location='@Url.Action("Run", "Kiosk", new { KioskID = Model.OriginalKioskID })'">OK!</button>
</div>

KioskWebWizard/KioskWebWizard/Views/Kiosk/Run2.cshtml
@model KioskWebWizard.ViewModel.Kiosk.Run.KioskRun2ViewModelPart1

@{
    ViewData["Title"] = "Run2";
}

<h1>Run2</h1>

<div>
    <h4>KioskRun2ViewModelPart1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>